name: test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test-check:
    name: runner / ansible-lint (github-check)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        continue-on-error: true
        id: test
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
          targets: ./testdata/**/*.yml

      # The check is expected to fail on the test data
      - name: Check return codes
        if: success() || failure ()
        run: |
          ansible_lint_return="${{ steps.test.outputs.ansible-lint-return-code }}"
          reviewdog_return="${{ steps.test.outputs.reviewdog-return-code }}"

          if [ "$ansible_lint_return" -gt 0 ]; then
            echo "ansible-lint correctly returned failure ${ansible_lint_return}"
          else
            echo "ansible-lint returned ${ansible_lint_return}, expected greater than '0'. Failing..."
            exit 1
          fi

          if [ "$reviewdog_return" -eq 0 ]; then
            echo "reviewdog correctly returned success: ${reviewdog_return}"
          else
            echo "reviewdog returned ${reviewdog_return}, expected '0'. Failing..."
            exit 1
          fi

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / ansible-lint (github-pr-check)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        continue-on-error: true
        id: test
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: info
          targets: ./testdata/**/*.yml

      # The check is expected to fail on the test data
      - name: Check return codes
        if: success() || failure ()
        run: |
          ansible_lint_return="${{ steps.test.outputs.ansible-lint-return-code }}"
          reviewdog_return="${{ steps.test.outputs.reviewdog-return-code }}"

          if [ "$ansible_lint_return" -gt 0 ]; then
            echo "ansible-lint correctly returned failure ${ansible_lint_return}"
          else
            echo "ansible-lint returned ${ansible_lint_return}, expected greater than '0'. Failing..."
            exit 1
          fi

          if [ "$reviewdog_return" -eq 0 ]; then
            echo "reviewdog correctly returned success: ${reviewdog_return}"
          else
            echo "reviewdog returned ${reviewdog_return}, expected '0'. Failing..."
            exit 1
          fi

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / ansible-lint (github-pr-review)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./
        continue-on-error: true
        id: test
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: info
          targets: ./testdata/**/*.yml

      # The check is expected to fail on the test data
      - name: Check return codes
        if: success() || failure ()
        run: |
          ansible_lint_return="${{ steps.test.outputs.ansible-lint-return-code }}"
          reviewdog_return="${{ steps.test.outputs.reviewdog-return-code }}"

          if [ "$ansible_lint_return" -gt 0 ]; then
            echo "ansible-lint correctly returned failure ${ansible_lint_return}"
          else
            echo "ansible-lint returned ${ansible_lint_return}, expected greater than '0'. Failing..."
            exit 1
          fi

          if [ "$reviewdog_return" -eq 0 ]; then
            echo "reviewdog correctly returned success: ${reviewdog_return}"
          else
            echo "reviewdog returned ${reviewdog_return}, expected '0'. Failing..."
            exit 1
          fi
